[package]
authors = ["Martin Pool <mbp@sourcefrog.net>"]
description = "A robust backup tool."
edition = "2018"
homepage = "https://github.com/sourcefrog/conserve/"
keywords = ["archive", "backup"]
license = "GPL-2.0"
name = "conserve"
readme = "README.md"
repository = "https://github.com/sourcefrog/conserve/"
version = "0.6.15"

[[bin]]
doc = false
name = "conserve"
test = false

[dependencies]
blake2-rfc = "0.2.18"
cachedir = "0.3"
chrono = "0.4.19"
derive_more = "0.99"
filetime = "0.2"
globset = "0.4.5"
hex = "0.4.2"
itertools = "0.10"
lazy_static = "1.4.0"
mutants = "0.0.3"
rayon = "1.3.0"
readahead-iterator = "0.1.1"
regex = "1.3.9"
semver = "1"
serde_json = "1"
snap = "1.0.0"
structopt = "0.3"
tempfile = "3"
thiserror = "1.0.19"
thousands = "0.2.0"

[dependencies.nutmeg]
version = "0.0.3-pre"
git = "https://github.com/sourcefrog/nutmeg.git"

[dependencies.serde]
features = ["derive"]
version = "1"

[dev-dependencies]
assert_cmd = "2.0"
assert_fs = "1.0"
cp_r = "0.4"
dir-assert = "0.2"
predicates = "2"
pretty_assertions = "1.0"
proptest = "1.0"
proptest-derive = "0.2"

[features]
blake2_simd_asm = ["blake2-rfc/simd_asm"]
debug_clap = ["structopt/debug"]

[lib]
doctest = false

[profile.release]
debug = true
