[package]
authors = ["Martin Pool <mbp@sourcefrog.net>"]
description = "A robust backup tool."
edition = "2018"
homepage = "https://github.com/sourcefrog/conserve/"
keywords = ["archive", "backup"]
license = "GPL-2.0"
name = "conserve"
readme = "README.md"
repository = "https://github.com/sourcefrog/conserve/"
version = "0.6.15-pre"

[[bin]]
doc = false
name = "conserve"
test = false

[dependencies]
blake2-rfc = "0.2.18"
chrono = "0.4.11"
crossterm = "0.19"
derive_more = "0.99.7"
filetime = "0.2"
globset = "0.4.5"
hex = "0.4.2"
itertools = "0.10.0"
lazy_static = "1.4.0"
rayon = "1.3.0"
readahead-iterator = "0.1.1"
regex = "1.3.9"
semver = "0.11"
serde_json = "1.0.53"
snap = "1.0.0"
structopt = "0.3.14"
tempfile = "3.1.0"
thiserror = "1.0.19"
thousands = "0.2.0"
unicode-segmentation = "1.6.0"

[dependencies.serde]
features = ["derive"]
version = "1.0.111"

[dev-dependencies]
assert_cmd = "2.0.1"
assert_fs = "1.0.0"
copy_dir = "0.1.2"
libc = "0.2.71"
predicates = "1.0.4"

[features]
blake2_simd_asm = ["blake2-rfc/simd_asm"]
debug_clap = ["structopt/debug"]

[lib]
doctest = false

[profile.release]
debug = true
