# Rust coverage measurement is a bit imprecise, so be generous in what counts as a
# failure.
coverage:
  status:
    project:
      default:
        informational: true
        target: auto
        threshold: 10%
    patch:
      default:
        informational: true
