on:
  push:
    paths:
      - '.github/workflows/install.yml'
  schedule:
    - cron: "17 0 * * 1"

jobs:
  cargo-install:
    strategy:
      matrix:
        locked: ["", "--locked"]
        # TODO: Enable s3 when it's released
        features: [""]
    runs-on: ubuntu-latest
    steps:
      - name: cargo-install
        run: |
          cargo install cargo-mutants ${{ matrix.locked }} --features=${{ matrix.features }}