name: cargo-mutants

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - ci-*

jobs:
  cargo-mutants:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cargo-mutants
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-mutants
      - name: Run mutant tests
        # Can't use --all-features here because BLAKE2 SIMD needs unstable...
        run: cargo mutants -j2 --no-shuffle
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: mutation-report
          path: mutants.out
