name: Rust

on: [push]

# see https://matklad.github.io/2021/09/04/fast-rust-builds.html
env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1
  RUST_BACKTRACE: short
  RUSTFLAGS: "-W rust-2021-compatibility"
  RUSTUP_MAX_RETRIES: 10

# TODO: Add -D warnings when that's clean on Windows.

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        features: ["", "s3"]

    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: Show version
        run: |
          rustup show
          cargo --version
          rustc --version
      - name: Build
        run:
          cargo build --all-targets --no-default-features --features=${{
          matrix.features }}
      - name: Test
        run:
          cargo test --no-default-features --features=${{ matrix.features }} --
          --include-ignored
      # Clippy and rustfmt are excellent tools but are turned off here because it's too
      # easy for PRs to fail due to irrelevant changes including Clippy flagging problems
      # that it did not notice before.
      # - name: clippy
      #   run: cargo clippy --all-targets -- -d clippy::all
      # - name: rustfmt
      #   run: cargo fmt --all -- --check

  cargo-mutants:
    runs-on: ubuntu-latest
    # Don't run expensive mutant tests until we know the build is clean.
    needs: tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install cargo-mutants
        uses: baptiste0928/cargo-install@v2
        with:
          crate: cargo-mutants
      - name: Run mutant tests
        # Can't use --all-features here because BLAKE2 SIMD needs unstable...
        # Don't use the S3 features because they require AWS credentials for realistic
        # testing.
        run:
          cargo mutants -j2 --no-shuffle -vV --cargo-arg --no-default-features
      - name: Archive results
        uses: actions/upload-artifact@v3
        with:
          name: mutation-report
          path: mutants.out
